PSI Food waste/Pages/Forms/AddLocation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Models;

namespace PSI_Food_waste.Pages.Forms
{
    public class AddLocationModel : PageModel
    {
        [BindProperty]
        public LocationModel UserLocation { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }
            RestaurantListModel.UserLocation = UserLocation.City;
            return RedirectToPage("/Forms/RestaurantList", new { UserLocation.City });
        }
    }
}

PSI Food waste/Pages/Forms/AddRestaurant.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Models;
using PSI_Food_waste.Services;
namespace PSI_Food_waste.Pages.Forms
{
    public class AddWorkerModel : PageModel
    {
        [BindProperty]
        public Restaurant NewRestaurant {  get; set; }

        public IRestaurantRepository _restaurantRepository;

        public IRegisterRepository _registerRepository;

        public AddWorkerModel(IRestaurantRepository restaurantRepository, IRegisterRepository registerRepository)
        {
            _restaurantRepository = restaurantRepository;
            _registerRepository = registerRepository;
        }
        public IActionResult OnGet()
        {
            ViewData["User"] = HttpContext.Session.GetString(key: "username");
            //authorization API
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("/Forms/LoginScreen");
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid == false)
            {
                return Page();
            }
            
            if(NewRestaurant.PictureUrl == null)
                NewRestaurant.PictureUrl = "https://www.linguahouse.com/linguafiles/md5/d01dfa8621f83289155a3be0970fb0cb";

            await _restaurantRepository.AddAsync(NewRestaurant);
            _registerRepository.CurrentUser.CreatedRestaurants.Add(NewRestaurant);
            //RestaurantVerifiedModel.Id = _restaurantRepository.GetID();
            //RestaurantVerifiedModel.Id = NewRestaurant.Id;
            Guid _id;
            _id = NewRestaurant.Id;
            //_restaurantRepository.GetID(NewRestaurant);
            return RedirectToPage("/Forms/RestaurantVerified", new { ID = _id });
        }
    }
}

PSI Food waste/Pages/Forms/LoginScreen.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Services;
using PSI_Food_waste.Models;

namespace PSI_Food_waste.Pages.Forms
{
    public class LoginScreenModel : PageModel
    {
        [BindProperty]
        public User NewUser { get; set; }

        [BindProperty]
        public string Msg { get; set; }

        public List<User> users = new List<User>
        {
            new User {Email = "admin" , Username = "admin", Password = "admin"},
            new User {Email = "abc" , Username = "abc", Password = "123"}
        };
        public RegisteredUser<RegisterForm> RegUsers { get; set; }

        public static RegisterForm CurrentUser { get; set; }

        public void OnGet()
        {
            ViewData["User"] = HttpContext.Session.GetString(key: "username");
            //RegUsers = RegisterService.GetAll();
            Msg = "";
        }
        public bool flag;
        public IActionResult OnPost()
        {
            //TODO FIX: EMPTY EMAIL FIELD WILL THROW EXCEPTION
            if (!ModelState.IsValid)
            {
                return Page();
            }
            RegUsers = RegisterService.GetAll();
            flag = false;

            for (int i = 0; i < RegUsers.Length(); i++)
            {
                if (NewUser.Email.Equals(RegUsers[i].Email))
                { 
                    if (NewUser.Password.Equals(RegUsers[i].Password))
                    {
                        CurrentUser = RegisterService.GetUserData(RegUsers[i].Email);
                        HttpContext.Session.SetString("username", RegUsers[i].Username);
                        return RedirectToPage("/Index");
                    }
                }
            }
            foreach (User user in users)
            {
                if (NewUser.Equals(user))
                {
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                HttpContext.Session.SetString("username", "admin");
                return RedirectToPage("/Index");
            }
            else
            {
                Msg = "Incorrect credentials";
                return Page();
            }
        }
    }
}

PSI Food waste/Pages/Forms/RegisterScreen.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Models;
using PSI_Food_waste.Services;

namespace PSI_Food_waste.Pages.Forms
{
    public class RegisterScreenModel : PageModel
    {
        

        public event EventHandler<string> OnSucessfullRegistrationEvent;

        public RegisteredUser<RegisterForm> RegisteredUsers { get; set; }/* = new RegisteredUser<RegisterForm>();*/

        public RegisterForm RegisteredUser { get; set; }

        [BindProperty]
        [Required]
        public string Email { get; set; }

        [BindProperty]
        [Required]
        public string Name { get; set; }
        [BindProperty]
        [Required]
        public string Pass { get; set; }
        [BindProperty]
        [Required]
        public int Num { get; set; }
        [BindProperty]
        public string Msg { get; set; }
        public string ErrorMsg { get; set; }

        public void OnGet()
        {
            ViewData["User"] = HttpContext.Session.GetString(key: "username");
            RegisteredUsers = RegisterService.GetAll();
            //if(RegisteredUsers == null)
            //{
            //RegisteredUsers = new RegisteredUser<RegisterForm>();
            //}
        }
        public IActionResult OnPost()
        {
            //email validation
            Regex regex3 = new Regex(@"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$");
            // Username validation
            Regex regex = new Regex(@"^\w{3,20}$");

            // password validation
            Regex regex2 = new Regex(@"^(?=.*[A-Za-z])(?=.*\d)(?=.*[\@$!%*#?&])[A-Za-z\d\@$!%*#?&]{8,}$");

            RegisteredUsers = RegisterService.GetAll();
            if (Email == null || !regex3.IsMatch(Email))
            {
                ErrorMsg = "Incorrect Email";
                return Page();
            }
            for (int i = 0; i < RegisteredUsers.Length(); i++)
            {
                if (Email.Equals(RegisteredUsers[i].Email))
                {
                    ErrorMsg = "This email already exists";
                    return Page();
                }
            }
            if (Name == null || !regex.IsMatch(Name))
            { 
                ErrorMsg = "Username must contain from 3 to 20 characters with no special characters";
                return Page();
            }
            if (Pass == null || !regex2.IsMatch(Pass))
            {
                ErrorMsg = "Password must contain atleast 8 characters, one letter and a special character";
                return Page();
            }
            else
            {
                RegisteredUser = new RegisterForm(new List<Restaurant>(), Email, Name, pass: Pass, favNum: Num);
                RegisterService.SetAll(this.RegisteredUser.AddToList(RegisteredUsers));
                RegistrationEventNotifier var = new(Email);
                return RedirectToPage("/Forms/LoginScreen");
            }
        }
        public void RaiseEvent(string mail)
        {
            OnSucessfullRegistrationEvent?.Invoke(this, mail);
        }
    }
}

PSI Food waste/Pages/Forms/RestaurantList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Models;
using PSI_Food_waste.Services;

namespace PSI_Food_waste.Pages.Forms
{
    public class RestaurantListModel : PageModel
    {
        public List<Restaurant> restaurants { get; set; }
        public List<Product> products { get; set; }

        [BindProperty]
        public string SearchByCity { get; set; }

        public string UserLocation { get; set; }

        [BindProperty]
        public string msg { get; set; }

        [BindProperty]
        public bool Login { get; set; }

        public IRestaurantRepository _restaurantRepository;

        public IRegisterRepository _registerRepository;
        public IProductRepository _productRepository;

        public RestaurantListModel(IRestaurantRepository restaurantRepository, IRegisterRepository registerRepository, IProductRepository productRepository)
        {
            _restaurantRepository = restaurantRepository;
            _registerRepository = registerRepository;
            _productRepository = productRepository;
        }

        public void OnGet(string City)
        {
                ViewData["User"] = HttpContext.Session.GetString(key: "username");
            SearchByCity = City;
            restaurants = _restaurantRepository.GetAll();
            products = _productRepository.GetAll();

            if (SearchByCity is null || SearchByCity.Equals("None"))
            {

            }
            else
            {
                restaurants = restaurants.Where((restaurants, SearchByCity) => restaurants.City.Equals(SearchByCity), SearchByCity);
            }
        }
        public void OnPostFilter(LocationModel loc)
        {
            products = _productRepository.GetAll();
            restaurants = _restaurantRepository.GetAll();
            ViewData["User"] = HttpContext.Session.GetString(key: "username");
            if (SearchByCity == "None")
            {

            }
            else
            {
                restaurants = restaurants.Where((restaurants, SearchByCity) => restaurants.City.Equals(SearchByCity), SearchByCity);
            }
        }
        public IActionResult OnPostSelect(Guid id)
        {
            return RedirectToPage("/Forms/RestaurantProducts", new { ID = id });
        }
        public IActionResult OnPostSubscribe(Guid id)
        {
            if (_registerRepository.CurrentUser.Username != null)
            {
                Restaurant restaurant = new Restaurant();
                restaurant = _restaurantRepository.Get(id);
                if (!_registerRepository.CurrentUser.SubscribedRestaurants.Contains(restaurant))
                {
                    _registerRepository.CurrentUser.SubscribedRestaurants.Add(restaurant);
                    return RedirectToAction("Get", new LocationModel { City = SearchByCity });
                }
                else
                    return RedirectToAction("OnPostFilter");
            }
            else
            {
                return RedirectToAction("OnPostFilter");
            }
        }
    }
}

PSI Food waste/Pages/Forms/RestaurantProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Models;
using PSI_Food_waste.Services;
using System.Collections.Generic;

namespace PSI_Food_waste.Pages.Forms
{
    public class RestaurantProductsModel : PageModel
    {
        public List<Product> products { get; set; }
        public Restaurant restaurant {  get; set; }
        public static int IdTest { get; set; }
        [BindProperty]
        public string searchCriteria { get; set; }

        public void OnGet()
        {
            restaurant = RestaurantServices.Get(id : IdTest);
            products = ProductService.GetList(id : IdTest);
        }
        public void OnPost()
        {
            //return RedirectToPage("/Forms/RestaurantProducts", new {searchCriteria = this.searchCriteria});
            restaurant = RestaurantServices.Get(id: IdTest);
            products = ProductService.GetList(id: IdTest);
        }
        public string GlutenFreeText(Product product) 
        {
            if (product.IsGlutenFree)
                return "Gluten Free";
            return "Not Gluten Free";
        }
    }
}

PSI Food waste/Pages/Forms/RestaurantVerified.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using PSI_Food_waste.Models;
using PSI_Food_waste.Services;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace PSI_Food_waste.Pages.Forms
{

    public class RestaurantVerifiedModel : PageModel
    {
        [BindProperty]
        public Product NewProduct { get; set; }

        public List<Product> products;

        [BindProperty]
        public static string Msg { get; set; } = "";

        public Action<Product> DiscountPrice; //= _productRepository.NewPrice;  //TODO: fix error

        public event EventHandler<ProductArgs> OnAddedProduct;
        public event EventHandler<ProductArgs> OnRemovedProduct;


        public IRestaurantRepository _restaurantRepository;

        public IProductRepository _productRepository;

        public RestaurantVerifiedModel(IProductRepository productRepository, IRestaurantRepository restaurantRepository)
        {
            _productRepository = productRepository;
            _restaurantRepository = restaurantRepository;
            DiscountPrice = _productRepository.NewPrice;
        }

        public string GlutenFreeText(Product product)
        {
            if (product.IsGlutenFree)
                return "Gluten Free";
            return "Not Gluten Free";
        }
        public void OnGet()
        {
            ViewData["User"] = HttpContext.Session.GetString(key: "username");
            _productRepository.SortProducts();
            products = _productRepository.GetList(_restaurantRepository.GetID());

        }
        public IActionResult OnPost()
        {
            OnAddedProduct += RestaurantVerifiedModel_OnAddedProduct;
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("/Forms/LoginScreen");
            }
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _productRepository.Add(NewProduct);
            DiscountPrice.Invoke(NewProduct);
            OnAddedProduct?.Invoke(this, new ProductArgs(NewProduct.Name, "has been added to the product list"));
            return RedirectToAction("Get");
        }
        private void RestaurantVerifiedModel_OnAddedProduct(object sender, ProductArgs e)
        {
            Msg = e.Name + " " + e.Msg;
        }
        public IActionResult OnPostDelete(int id)
        {
            OnRemovedProduct += RestaurantVerifiedModel_OnRemovedProduct;
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("/Forms/LoginScreen");
            }
            Product DelProduct = _productRepository.Get(id);
            OnRemovedProduct?.Invoke(this, new ProductArgs(DelProduct.Name, "was removed from the product list"));
            _productRepository.Delete(id);
            return RedirectToAction("Get");
        }

        private void RestaurantVerifiedModel_OnRemovedProduct(object sender, ProductArgs e)
        {
            Msg = e.Name + " " + e.Msg;
        }
    }
    public class ProductArgs : EventArgs
    {
        public string Msg;

        public string Name;
        public ProductArgs(string name, string msg)
        {
            Msg = msg;
            Name = name;
        }
    }
}

PSI Food waste/Pages/Forms/groupJoinTest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PSI_Food_waste.Models;
using PSI_Food_waste.Services;

namespace PSI_Food_waste.Pages.Forms
{
    public class groupJoinTestModel : PageModel
    {
        public List<Product> products { get; set; }
        public List<Restaurant> restaurants { get; set; }


        public void OnGet()
        {
            restaurants = RestaurantServices.GetAll();
            products = ProductService.GetAll();
        }
    }
}

PSI Food waste/Pages/Forms/AddLocation.cshtml
@page
@model PSI_Food_waste.Pages.Forms.AddLocationModel
@{
    ViewData["Title"] = "Add Location";
}

<h1>Add Location</h1>
<form method="post">
    <label asp-for="UserLocation.City">City</label>
    <select style="width:100px;"
            name="UserLocation.City" id="UserLocation.City">
        <option value="None">None</option>
        <option value="Vilnius">Vilnius</option>
        <option value="Kaunas">Kaunas</option>
        <option value="Klaipeda">Klaipeda</option>
        <option value="Panevežys">Panevežys</option>
        <option value="Šiauliai">Šiauliai</option>
    </select>

    <input type="text" asp-for="UserLocation.Street" placeholder="Street" />
    <button class="btn btn-primary" type="submit">Submit</button>
</form>

PSI Food waste/Pages/Forms/AddRestaurant.cshtml
@page
@model PSI_Food_waste.Pages.Forms.AddWorkerModel
@{
    ViewData["Title"] = "Restaurant login";
}
<h1>Add a worker</h1>

<form style="
        width:1200px;"
            method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All">
        </div>
    </div>
    <div style="
        width:1500px;"
            class = "form-group mb-0 align-middle">
        <label asp-for="NewRestaurant.Title">Name</label>
        <input type="text" asp-for="NewRestaurant.Title" class="mr-5">

        <label asp-for="NewRestaurant.City">City</label>
        <select style="width:100px;"
        name="NewRestaurant.City" id="NewRestaurant.City">
            <option value="Vilnius">Vilnius</option>
            <option value="Kaunas">Kaunas</option>
            <option value="Klaipeda">Klaipeda</option>
            <option value="Panevežys">Panevežys</option>
            <option value="Šiauliai">Šiauliai</option>
        </select>

        <label asp-for="NewRestaurant.Adress">Adress</label>
        <input type="text" asp-for="NewRestaurant.Adress" class="mr-5">

        <label asp-for="NewRestaurant.PictureUrl">Picture</label>
        <input type="url" asp-for="NewRestaurant.PictureUrl" class="mr-5">

        <button class="btn btn-primary">Submit</button>
    </div>
</form>

PSI Food waste/Pages/Forms/LoginScreen.cshtml
@page
@using PSI_Food_waste.Models
@model PSI_Food_waste.Pages.Forms.LoginScreenModel
@{
    //ViewData["uss"] = NewUser;
}
<div class="login-form">
    <h1 class="page-header">Login to your account</h1>
    <p>Not a member? <a asp-page="/Forms/RegisterScreen">Sign up now!</a></p>
    <form class="form" method="post">
        <div class="row">
            <div asp-validation-summary="All"></div>
        </div>
        <div class="form-group">
            <div class="input">
                <i class="fa fa-envelope icon"></i>
                <input type="text" asp-for="NewUser.Email" class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="form-group">
            <div class="input">
                <i class="fa fa-lock icon"></i>
                <input type="password" asp-for="NewUser.Password" class="form-control" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="confirm-buttom">Login</button>
            <label style="color:red">@Model.Msg</label>
        </div>
    </form>
</div>

PSI Food waste/Pages/Forms/RestaurantList.cshtml
@page
@model PSI_Food_waste.Pages.Forms.RestaurantListModel
@{
}
<div class="restaurant-list-page">
    <div class="restaurant-list-page-header">
    <h2 class="page-heading">Restaurants available</h2>

    <form class="filter" method="post" asp-page-handler="Filter">
        <select style="width:100px;"
                name="SearchByCity" id="SearchByCity">
            <option value="None">None</option>
            <option value="Vilnius">Vilnius</option>
            <option value="Kaunas">Kaunas</option>
            <option value="Klaipeda">Klaipeda</option>
            <option value="Panevežys">Panevežys</option>
            <option value="Šiauliai">Šiauliai</option>
        </select>
        <button class="filter-btn"><i class="fa-sharp fa-solid fa-filter"></i></button>
    </form>
    </div>

    @{
        var productsWithRestaurant = Model.products.Join(Model.restaurants,
        p => p.RestId,
        r => r.Id,
        (p, r) => new { p.Name, r.Title, r.Id, r.PictureUrl,r.Adress, p.DiscountedPrice, p.Price, p.Discount });

        var productsByRestaurant = productsWithRestaurant.GroupBy(p => new { p.Title, p.PictureUrl, p.Id, p.Adress});
    }

    <div id="product-grid" class="card-columns">
        @foreach (var productGroup in productsByRestaurant)
        {
            <a asp-page="/Forms/RestaurantProducts" class="restaurant-link" asp-route-id="@productGroup.Key.Id" method="post">
                <div class="card">
                    <div class="card-img" style="background-image: url('@productGroup.Key.PictureUrl')"></div>
                    <div class="card-body">

                        <div class="card-text">
                            <h4>@productGroup.Key.Title (@productGroup.Key.Adress)</h4>
                            @*<form>
                                <label class="col-sm-8 align-items-sm-start" style="font-size:170%;">@productGroup.Key.Title</label>
                                <button class="btn-primary" style="height: 30px; width:70px">View</button>
                                </form>*@
                            @*<h6>@productGroup.Key.Title: @productGroup.Count() products</h6>*@
                            @foreach (var product in productGroup.Take(2))
                            {
                                <p></p>
                                <label class="card-label">@product.Name</label>
                                <label class="card-label" style="color:red;">-@product.Discount%</label>
                            }
                        </div>
                        <div class="btn-group">
                            @*<label class="col-sm-9" style="color:black; font-size:140%;">@productGroup.Key.Title</label>*@
                            <div class="btn-sm">
                                <form method="post" asp-page-handler="Select" asp-route-id="@productGroup.Key.Id">
                                    <button class="view-button">View</button>
                                </form>
                            </div>

                            @if (ViewData["User"] != null)
                            {
                                bool isSubed = false;
                                @foreach (var data in @Model._registerRepository.CurrentUser.SubscribedRestaurants)
                                {
                                    if (productGroup.Key.Id.Equals(data.Id))
                                        isSubed = true;

                                }
                                if (isSubed)
                                {
                                    <p></p>
                                }
                                else
                                {
                                    <div class="btn-sm">
                                        <form method="post" asp-page-handler="Subscribe" asp-route-id="@productGroup.Key.Id">
                                            <button class="btn btn-primary">Subscribe</button>
                                        </form>
                                    </div>

                                }
                            }
                            else
                            {
                            }
                        </div>
                    </div>

                </div>
            </a>
        }
    </div>

    @*<table class="table mt-5">
        <thead>
        <tr>
        <th scope="col">City</th>
        <th scope="col">Restaurant name</th>
        <th scope="col">Restaurant adress</th>
        <th scope="col">See products</th>
        <th scope="col">subscriptions</th>
        </tr>
        </thead>

        @foreach (var restaurant in Model.restaurants)//.Where((restaurant, Model.SearchByCity) => restaurant.City.Equals(SearchByCity), SearchByCity))
        {
        <tr>
        <td>@restaurant.City</td>
        <td>@restaurant.Title</td>
        <td>@restaurant.Adress</td>
        <td>
        <form method="post" asp-page-handler="Select" asp-route-id="@restaurant.Id">
        <button class="btn btn-primary">Select</button>
        </form>
        </td>
        @if (ViewData["User"] != null)
        {
        if (@Model._registerRepository.CurrentUser.SubscribedRestaurants.Contains(restaurant))
        {
        <td>You are subscribed to this restaurant</td>
        }
        else
        {
        <td>
        <form method="post" asp-page-handler="Subscribe" asp-route-id="@restaurant.Id">
        <button class="btn btn-primary">Subscribe</button>
        </form>
        </td>
        }
        }
        else
        {
        <td>Login to subscribe</td>
        }
        </tr>
        }
        </table>*@
    @*<table>
        <tr>
        @if (ViewData["User"] != null)
        {
        <td>@Model._registerRepository.CurrentUser.Email</td>
        <td>@Model._registerRepository.CurrentUser.Username</td>
        @foreach (var data in @Model._registerRepository.CurrentUser.SubscribedRestaurants)
        {
        <td>@Model._registerRepository.CurrentUser.Email</td>
        <td>@Model._registerRepository.CurrentUser.Username</td>
        @foreach (var data in @Model._registerRepository.CurrentUser.SubscribedRestaurants)
        {
        <td>@data.Title </td>
        }
        }
        </tr>
        </table>*@

</div>

PSI Food waste/Pages/Forms/RestaurantVerified.cshtml
@page
@using PSI_Food_waste.Models
@model PSI_Food_waste.Pages.Forms.RestaurantVerifiedModel
@{
    ViewData["Title"] = "Products";
}

<h1>Product list</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <label asp-for="NewProduct.Name">Name</label>
        <input type="text" asp-for="NewProduct.Name" class="mr-5">
        <label asp-for="NewProduct.Size">Size</label>
        <select asp-for="NewProduct.Size" asp-items="Html.GetEnumSelectList<ProductSize>()" class="mr-5"></select>
        <label asp-for="NewProduct.Price"></label>
        <input asp-for="NewProduct.Price" class="mr-5" />

        <label asp-for="NewProduct.Discount"></label>
        <input asp-for="NewProduct.Discount" class="mr-5" />
        <label asp-for="NewProduct.IsGlutenFree">Gluten Free</label>
        <input type="checkbox" asp-for="NewProduct.IsGlutenFree" class="mr-5">
        <button class="btn btn-primary">Add</button>
    </div>
</form>
<h3 style="color:green">@RestaurantVerifiedModel.Msg</h3>
<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Discounted Price</th>
            <th scope="col">Discount %</th>
            <th scope="col">Size</th>
            <th scope="col">Gluten Free</th>
            <th scope="col"></th>
        </tr>
    </thead>
    @foreach (var product in Model.products)
    {
       //@product.Price = newPrice.Invoke(product.Price, product.Discount);
        <tr>
            <td>@product.Name</td>
            <td>@($"{product.DiscountedPrice:C}")</td>
            <td>@($"{(product.Discount/100d):P0}")</td>
            <td>@product.Size</td>
            <td>@Model.GlutenFreeText(product)</td>
            <td>
                <form method="post" asp-page-handler="Delete" asp-route-id="@product.PrId">
                    <button class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

PSI Food waste/Pages/Forms/Sandbox.cshtml
@page
@model PSI_Food_waste.Pages.Forms.Sandbox
@{
}


@{     @*var query =
        Model.restaurants.GroupJoin(products,
                                    restaurant => restaurant,
                                    product => product.RestId)*@
//var query =
//    Model.restaurants.GroupJoin(Model.products,
//                                restaurant => restaurant,
//                                product => product.RestId,
//                                (restaurant, productCollection) =>
//                                     new
//                                     {
//                                         RestaurantName = restaurant.Title,
//                                         Pets = productCollection.Select(product =>  product.RestId)
//                                     });
//foreach (var obj in query)
//    {

//    }
    <h4>group join</h4>

    var query = from restaurant in Model.restaurants
                join product in Model.products on restaurant.Id equals product.RestId into productCollection
                select new { RestaurantName = restaurant.Title, Products = productCollection };

    foreach (var v in query)
    {
                <p>@v.RestaurantName</p>
        foreach (Models.Product product in v.Products)
        {
                    <p>---@product.Name</p>
        }
    }

    <h4>indexed demo</h4>
       
    var demoCollection = new Models.IndexDemo<string>();

    demoCollection[0] = "hello";
    demoCollection[1] = ", ";
    demoCollection[2] = "world";

    for (int i = 0; i < 4; ++i)
    {
        <label>@demoCollection[i]</label>
    }

    <h4>struct demo</h4>

    List<Models.StructDemo> users = new List<Models.StructDemo>()
    {
        new Models.StructDemo("User"),
        new Models.StructDemo("User", "2"),
        new Models.StructDemo("User", "3", 10),
        new Models.StructDemo("User4", age: 10),
        new Models.StructDemo("User5", age: 10),
        new Models.StructDemo(lname: "6", age: 10, name: "User")
    };

    foreach(var user in users)
            {
                <p>@user.ToString()</p>
            }

    <h4>type conversion demo</h4>
    double _double  = 2.5;
    int _int = (int)_double;
    <p>@_double</p>

    var first = 32769;
    short second = (short)first;
    <p>@second</p>

    long _long = first;
    <p>@_long</p>
}